# Part A

## Question 1

In [ ]:
# Use R software to answer the following questions and save all R codes you use in an R script.
# (a) Calculate the probability that the random variable X takes the val ue 3, if X ~ Binomial (10, Q.3) distribution.
dbinom(3, 10, 0.3)

# (b) Calculate the probability of X takes a value less than 1.5 if X ~Uniform(0,2).
pbinom(1.5, 10, 0.3)

# (c) Generate 100 random values from a Uniform (0, 2) distribution.
# (i). Find the mean and the variance of the generated values
x < -runif(100, 0, 2)
mean(x)
var(x)

# (ii). Compare the mean and the variance obtained in (i) with theoretical values of the Uniform(0,2) [20 Marks]
mu < -1
v < -(2 - 0) ^ 2 / 12
v

# (d) A car manufacturer claims that his new car model runs 20 km per liter. The number ofkm
# p er liter for a simple random sample of size 10 cars are found to be ,
# 20, 21, 22, 13, 14, 19, 23, 22, 18, 16
# Suppose you need to test the car manufactures claim at 5% significance level.
# (i) Write the null and the alternative hypotheses clearly.
"H_0: mu >= 20"
"H_1: mu < 20"

# (ii) What is the test statistic value in testing the manufacturer's claim?
t.test(c(20, 21, 22, 13, 14, 19, 23, 22, 18, 16), mu=20, alternative="less")

# (iii) Write the conclusion based on the p-value obtained using R software.
"since p-value > 0.05, we fail to reject the null hypothesis. Therefore, we do not have enough evidence to reject the manufacturer's claim that the car runs 20 km per liter."

[1] 0.2668279

[1] 0.1493083

[1] 0.9679184

[1] 0.3387512

[1] 0.3333333

[1] "H_0: mu >= 20"

[1] "H_1: mu < 20"

	One Sample t-test

data:  c(20, 21, 22, 13, 14, 19, 23, 22, 18, 16)
t = -1.0874, df = 9, p-value = 0.1526
alternative hypothesis: true mean is less than 20
95 percent confidence interval:
     -Inf 20.82289
sample estimates:
mean of x
     18.8

[1] "since p-value > 0.05, we fail to reject the null hypothesis. Therefore, we do not have enough evidence to reject the manufacturer's claim that the car runs 20 km per liter."

# Question 2

In [ ]:
# (a) Suppose you are testing the normality of the set of numbers given below using Anderson
# darling test.
# 156,82,56,34,69,64,76,48,60, 143
# (i) What is p-value you obtain for the test in R-software?
library(nortest)
x <- c(156, 82, 56, 34, 69, 64, 76, 48, 60, 143)
ad.test(x)

# (ii) What conclusion you can make based on the obtained p-value?
"Since the p-value is less than 0.05, we reject the null hypothesis that the data is normally distributed. 
Therefore, we conclude that the data does not follow a normal distribution."

# (iii) If the above given data do not distribute normally do a suitable transformation to make them distributed normally.
x <- log(x)
ad.test(x)

	Anderson-Darling normality test

data:  x
A = 0.79015, p-value = 0.02617

[1] "Since the p-value is less than 0.05, we reject the null hypothesis that the data is normally distributed. \nTherefore, we conclude that the data does not follow a normal distribution."

	Anderson-Darling normality test

data:  x
A = 0.33629, p-value = 0.4276

In [ ]:
# (b)
# (i) Write two properties of a good random_number generator.

"A good random number generator should produce numbers that are uniformly distributed over the specified range 
and should be reproducible, meaning that the same seed will always produce the same sequence of random numbers."

# (ii) Taking the _seed as 2468 generate first 6 random numbers using mid square method.

[1] "A good random number generator should produce numbers that are uniformly distributed over the specified range \nand should be reproducible, meaning that the same seed will always produce the same sequence of random numbers."

In [ ]:
# c) A researcher wants to test whether identical twins, separated at birth and raised by different
# famili€s, show similar IQ scores. So he has taken 8 such twin pairs a~d one twin in each pair
# was randomly selected and let him/her live with the parents and the other one was se nt to live
# with a different family. After a certain period the same IQ te st was given to both sets of twins.
# The observed results are in Table l.
# Table 1
# | Twin Pair | IQ (Same Family) | IQ (Different Family) |
# |-----------|------------------|------------------------|
# | 1         | 103              | 107                    |
# | 2         | 92               | 90                     |
# | 3         | 108              | 10                     |
# | 4         | 129              | 128                    |
# | 5         | 114              | 112                    |
# | 6         | 121              | 118                    |
# | 7         | 86               | 90                     |
# | 8         | 88               | 89                     |
# Using R software test at 5% level of significance whether IQ scores are different among the
# twins lived with their own family .an d the twins raised by a different family.
"h0:mu-mu=0"
"h1:mu-mu/=0"

c(103, 92, 108, 129, 114, 121, 86, 88) -> same_family
c(107, 90, 10, 128, 112, 118, 90, 89) -> different_family
diff <- same_family - different_family
# t.test(diff, mu = 0, alternative = "two.sided")
t.test(same_family,different_family, alternative = "two.sided", paired=TRUE)

[1] "h0:mu-mu=0"

[1] "h1:mu-mu/=0"

	Paired t-test

data:  same_family and different_family
t = 0.98539, df = 7, p-value = 0.3573
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -16.97126  41.22126
sample estimates:
mean difference
         12.125

# Question 3

In [ ]:
# (a) A coordinator of a degree program needs to test whether there is an association between gender
# and the class obtained for the degree. He uses data in the following Table, to test this
# association.
# | Class         | Male | Female | Total |
# |---------------|------|--------|-------|
# | First Class   | 5    | 10     | 15    |
# | Second Class  | 20   | 15     | 35    |
# | General Pass  | 25   | 25     | 50    |
# | **Total**     | 50   | 50     | 100   |
# Perform a suitable statistical test using R software and check whether there is an association
# between gender and the class obtained for the degree.

data <- matrix(c(5, 10, 20, 15, 25, 25), nrow = 3, byrow = TRUE)
rownames(data) <- c("First Class", "Second Class", "General Pass")
colnames(data) <- c("Male", "Female")
data_table <- as.table(data)
chisq.test(data_table)

	Pearson's Chi-squared test

data:  data_table
X-squared = 2.381, df = 2, p-value = 0.3041

# Part B

## Question 3

In [ ]:
%load_ext sql
%sql mysql+mysqldb://root:my-secret-pw@127.0.0.1/testdb
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [5]:
%%sql
# (b) Write complete MySQL codes to do the following.
# i) Create a database named CJM2022
CREATE DATABASE If NOT EXISTS CJM2022;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
1 rows affected.

[]

In [10]:
%%sql
# ii) Create a table named studentData with the following variables.
# Table 1: Variable Information
# | Variable Name | Type      | Length |
# |---------------|-----------|--------|
# | ID            | Character | 3      |
# | Name          | Character | 15     |
# | Gender        | Character | 1      |
# | Height        | Integer   | 3      |
# | Age           | Integer   | 2      |
CREATE TABLE IF NOT EXISTS studentData (
    ID CHAR(3),
    Name VARCHAR(15),
    Gender CHAR(1),
    Height INT,
    Age INT
);


# iii) Show the studentData table. [5 marks]
SELECT * FROM studentData;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
0 rows affected.
0 rows affected.

[]

In [14]:
%%sql
# iv) Assume that 10 records were inserted to the studentData. Get the structure of the
# studentData table. [5 marks]
DESCRIBE studentData;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
5 rows affected.

[('ID', 'char(3)', 'YES', '', None, ''),
 ('Name', 'varchar(15)', 'YES', '', None, ''),
 ('Gender', 'char(1)', 'YES', '', None, ''),
 ('Height', 'int', 'YES', '', None, ''),
 ('Age', 'int', 'YES', '', None, '')]

In [15]:
%%sql
# v) Add the followi ng new record to the studentData table.
# ID - 025, Name - Macheal, Gender - F, Height - 165, Age - 26
INSERT INTO studentData (ID, Name, Gender, Height, Age) VALUES ('025', 'Macheal', 'F', 165, 26);

 * mysql+mysqldb://root:***@127.0.0.1/testdb
1 rows affected.

[]

# Question 4

In [35]:
# (a) Insta ll the 'sqldf and 'PASWR' package. Load the packages. Also load the 'titanic3' data
# from 'PASWR' package. [5 marks]
# install.packages("sqldf")
# install.packages("PASWR")
library(sqldf)
library(PASWR)

data(titanic3)

# (b) Count the number of rows in the 'titanic 3' data using sqldf function. Compare yo ur answer
# with the R counterpart. [15 marks]
sqldf("SELECT COUNT(*) as n FROM titanic3")

# (c) Select al! the columns and rows from 'titanic3' data and put it into a variable ' TitanicData'.
# [10 marks]
TitanicData <- sqldf("SELECT * FROM titanic3")

# (d) Select the first two columns of the 'titanic3' data and put it into a variable 'TitanicFirst2Cols'. [10 marks]
sqldf("SELECT pclass, survived FROM titanic3 limit 6")

# (e) Print the first 6 rows of the 'titanic3' dataset using sqldf function. [IO marks]
sqldf("SELECT * FROM titanic3 limit 6")

# (f) Count the number of people in the 'titanic3' dataset where the sex is female. (IO marks]
sqldf("SELECT COUNT(*) as F FROM titanic3 WHERE sex='female'")

# (g) Count the number of people in the 'titanic3' dataset where the sex 'is male and the port of embarkment is Cherbourg. [15 marks]
sqldf("SELECT COUNT(*) as n FROM titanic3 WHERE sex='male' AND embarked='Cherbourg'")

# (h) Calculate the average fare for each passenger class. [IO marks]
sqldf("SELECT pclass, AVG(ticket) FROM titanic3 group by pclass")

# (i) Find the proportion of survivors for each gender? Who survived most? [15 marks]"
sqldf("SELECT sex, COUNT(sex) as n FROM titanic3 group by sex")

  n
1 1309

  pclass survived
1 1st    1
2 1st    1
3 1st    0
4 1st    0
5 1st    0
6 1st    1

  pclass survived name                            sex    age     sibsp parch
1 1st    1        Allen, Miss. Elisabeth Walton   female 29.0000 0     0
2 1st    1        Allison, Master. Hudson Trevor  male    0.9167 1     2
3 1st    0        Allison, Miss. Helen Loraine    female  2.0000 1     2
4 1st    0        Allison, Mr. Hudson Joshua Crei male   30.0000 1     2
5 1st    0        Allison, Mrs. Hudson J C (Bessi female 25.0000 1     2
6 1st    1        Anderson, Mr. Harry             male   48.0000 0     0
  ticket fare     cabin   embarked    boat body home.dest
1 24160  211.3375 B5      Southampton 2     NA  St Louis, MO
2 113781 151.5500 C22 C26 Southampton 11    NA  Montreal, PQ / Chesterville, ON
3 113781 151.5500 C22 C26 Southampton       NA  Montreal, PQ / Chesterville, ON
4 113781 151.5500 C22 C26 Southampton      135  Montreal, PQ / Chesterville, ON
5 113781 151.5500 C22 C26 Southampton       NA  Montreal, PQ / Chesterville, ON
6 19952   26.5500 E12     Southampton 3     NA  New York, NY

  F
1 466

  n
1 157

  pclass AVG(ticket)
1 1st     42250.66
2 2nd    112353.72
3 3rd    273006.36

  sex    n
1 female 466
2 male   843

**_End of the paper_**