# Part A

## Question 01

In [ ]:
# a) A coin is biased so that the probability of obtaining a head is 2/3. The coin is tossed four
# times.
# (i) Find the probability of obtaining exactly two heads.
dbinom(2, 4, prob=2 / 3)
# (ii) Find the probability of obtaining less than two heads.
pbinom(1, 4, prob=2 / 3)
dbinom(0, 4, prob=2 / 3) + dbinom(1, 4, prob=2 / 3)

[1] 0.2962963

[1] 0.1111111

[1] 0.1111111

In [ ]:
# (b) An ordinary die is thrown seven times. Find the probability of obtaining exactly three sixes.
dbinom(3, 7, prob=1 / 6)

[1] 0.07814286

In [ ]:
# (c) If X~ N (100,36) and P(X>a) = 0.1093, find the value of a.
p = 1 - 0.1093
a < -qnorm(p, mean=100, sd=36)
a
# 1-pnorm(144.28, mean = 100, sd = 36)

[1] 144.2893

In [ ]:
# (d) The lengths of certain items follow a normal distribution with mean μ cm and standard
# deviation 6 cm. It is known that 4.78% of the items have a length less than 82cm. Find the
# value of the mean μ.
qnorm(0.95)

mu < -82 - qnorm(0.048) * 6
mu

[1] 1.644854

[1] 91.98738

In [ ]:
# (e) Write R commands to obtain the following outputs.
# (i) 1 2 1 2 1 2 1 2
rep(1:2, 4)

# (ii) 3 3 3 3 5 5 5 5
rep(c(3, 5), each = 4)

[1] 1 2 1 2 1 2 1 2

[1] 3 3 3 3 5 5 5 5

## Question 02

In [ ]:
# a) The shortest time recorded by an athlete in a 400m race is called their personal best (PB).
# The PBs of the athletes in a large athletics club are normally distributed with mean 49.2 seconds and standard deviation 2.8 seconds.

# (i) Find the probability that a randomly chosen athlete from this club has a PB greater than 46 seconds. [20 marks]
1 - pnorm(46, mean=49.2, sd=2.8)

# (ii) Three athletes from the club are chosen at random. Find the probability that exactly 2 have PBs of less than 46 seconds. [30 marks]
dbinom(2, 3, pnorm(46, mean=49.2, sd=2.8))

[1] 0.873451

[1] 0.04196401

In [ ]:
# b) In a very small empirical study a sample from a random variable X is observed.
# (1.28, 0.54, 0.56, 1.36, 0.55, 0.37, 0.43, 0.46, 0.62, 0.54, 0.54, 0.51, 0.44, 0.68, 0.55, 0.30)

# (i) Estimate the expected value of X.
x = c(
    1.28,
    0.54,
    0.56,
    1.36,
    0.55,
    0.37,
    0.43,
    0.46,
    0.62,
    0.54,
    0.54,
    0.51,
    0.44,
    0.68,
    0.55,
    0.30,
)
mean_x = mean(x)
mean_x

# (ii) Calculate the sample standard deviation.
sd(x)

# (iii) Check the normality of the X using Shapiro Wilk Normality test and write p-value obtained.
shapiro.test(x)

# (iv) Calculate a 95% confidence interval for the expected value of X assuming that X is Normally distributed. [50 marks]
e = qt(0.975, df=length(x) - 1) * sd(x) / sqrt(length(x))
c(mean_x - e, mean_x + e)

[1] 0.608125

[1] 0.2930579

	Shapiro-Wilk normality test

data:  x
W = 0.70439, p-value = 0.0001887

[1] 0.4519655 0.7642845

## Question 03

In [ ]:
# (a) Below is a part of a data set named ProductData.xlsx. Import the data set into R- Studio.
# | ProductID | Product | Wattage | Life Hours | Brand   | Unit Cost (Rs) |
# |-----------|---------|---------|------------|---------|----------------|
# |     1     | Bulb    |   200   |    3000    | Horizon |      450       |
# |     2     | Neon    |   100   |    2000    | Horizon |      250       |
# |     3     | Spot    |    60   |    4000    | Horizon |      500       |
# |     4     | Neon    |    10   |    8000    | Sunbeam |       80       |
# |     5     | Bulb    |    80   |    1000    | Horizon |      260       |
# |     6     | Spot    |   100   |    1500    | Horizon |      175       |
# |     7     | Spot    |   200   |    3000    | Horizon |      250       |
# |     8     | Spot    |    25   |    2000    | Sunbeam |      500       |
# |     9     | Bulb    |   200   |    3000    | Sunbeam |      550       |
# |    10     | Neon    |   100   |    2000    | Sunbeam |      180       |
# (i) Write the R command that you can use to see the number of data records and
# variables in the data-frame. [10 marks]

ProductData <- data.frame(
  ProductID = 1:10,
  Product = c("Bulb", "Neon", "Spot", "Neon", "Bulb", "Spot", "Spot", "Spot", "Bulb", "Neon"),
  Wattage = c(200, 100, 60, 10, 80, 100, 200, 25, 200, 100),
  Life_Hours = c(3000, 2000, 4000, 8000, 1000, 1500, 3000, 2000, 3000, 2000),
  Brand = c("Horizon", "Horizon", "Horizon", "Sunbeam", "Horizon", "Horizon", "Horizon", "Sunbeam", "Sunbeam", "Sunbeam"),
  Unit_Cost_Rs = c(450, 250, 500, 80, 260, 175, 250, 500, 550, 180)
)

# (ii) Suppose the wattage value with the ProductID equals 4 is entered incorrectly and
# it should be corrected as 100, write a R command to make the correction. [05 marks]
ProductData[4, "Wattage"] <- 4

# (iii) Calculate the average life hours for the two brands Horizon and Sunbeam. [05 marks]
tapply(ProductData$Life_Hours, ProductData$Brand, mean)

# (iv) Test at 5% significance level whether the life hours are different for the brands
# Horizon and Sunbeam (Clearly define your Hypotheses and interpret the output).
t.test(Life_Hours ~ Brand, data = ProductData)

# (v) Test at 5% significance level whether the life hours are different for the different
# products (Clearly define your Hypotheses and interpret the output). [15 marks]
anova_result <- aov(Life_Hours ~ Product, data = ProductData)
summary(anova_result)

 Horizon  Sunbeam
2416.667 3750.000

	Welch Two Sample t-test

data:  Life_Hours by Brand
t = -0.88507, df = 3.6104, p-value = 0.4311
alternative hypothesis: true difference in means between group Horizon and group Sunbeam is not equal to 0
95 percent confidence interval:
 -5700.110  3033.444
sample estimates:
mean in group Horizon mean in group Sunbeam
             2416.667              3750.000

            Df   Sum Sq Mean Sq F value Pr(>F)
Product      2  4870833 2435417   0.562  0.594
Residuals    7 30354167 4336310

# Part B

## Question 03

In [ ]:
%load_ext sql
%sql mysql+mysqldb://root:my-secret-pw@127.0.0.1/testdb
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [11]:
%%sql
show databases;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
8 rows affected.

[('company',),
 ('information_schema',),
 ('msc2025',),
 ('mysql',),
 ('performance_schema',),
 ('schoolDB',),
 ('sys',),
 ('testdb',)]

In [33]:
%%sql
# (b) Write complete MySQL codes to do the following.
# (i) Create a database named CIM2023. [05 marks]
create database if not exists CIM2023;

# (ii) Create a table named orderData with the following variables.[15 marks]
# Table 1: Variable Information
# | Variable Name |   Type   | Length |
# |---------------|----------|--------|
# | ord_no        | character|   5    |
# | purch_amt     | float    |   8    |
# | ord_date      | date     |   —    |
# | customer_id   | character|   4    |
# | salesman_id   | character|   4    |

create table if not exists orderData (
    ord_no char(5),
    purch_amt float(8),
    ord_date date,
    customer_id char(4),
    salesman_id char(4)
);

# (iii) Show the orderData table. [05 marks]
select * from orderData;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
1 rows affected.
0 rows affected.
0 rows affected.

[]

In [48]:
%%sql
# Assume that orderData table is in the following form.
# | ord_no | purch_amt |  ord_date  | customer_id | salesman_id |
# |--------|-----------|------------|-------------|-------------|
# | 70001  |   150.50  | 2012-10-05 |     3005    |     5002    |
# | 70009  |   270.65  | 2012-09-10 |     3001    |     5005    |
# | 70002  |    65.26  | 2012-10-05 |     3002    |     5001    |
# | 70004  |   110.50  | 2012-08-17 |     3009    |     5003    |
# | 70007  |   948.50  | 2012-09-10 |     3005    |     5002    |
# Figure 1: orderData Table
# (iv) Get the structure of the orderData table. [05 marks]

delete from orderData;
insert into orderData (ord_no, purch_amt, ord_date, customer_id, salesman_id) values
('70001', 150.50, '2012-10-05', '3005', '5002'),
('70009', 270.65, '2012-09-10', '3001', '5005'),
('70002', 65.26, '2012-10-05', '3002', '5001'),
('70004', 110.50, '2012-08-17', '3009', '5003'),
('70007', 948.50, '2012-09-10', '3005', '5002');
 
describe orderData;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
10 rows affected.
5 rows affected.
5 rows affected.

[('ord_no', 'char(5)', 'YES', '', None, ''),
 ('purch_amt', 'float', 'YES', '', None, ''),
 ('ord_date', 'date', 'YES', '', None, ''),
 ('customer_id', 'char(4)', 'YES', '', None, ''),
 ('salesman_id', 'char(4)', 'YES', '', None, '')]

In [42]:
%%sql
# (v) Write MySQL codes to print the average purchase amount of all orders. [10 marks]
select avg(purch_amt) as average_purchase_amount from orderData;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
1 rows affected.

[(309.08199920654295,)]

In [49]:
%%sql
# (vi) Add the following new record to the orderData table.

# order_no – 7008, purch_amt– 700.3, ord_date – 2012-09-27, customer_id – 3004,
# salesman_id – 5004 [10 marks]

insert into orderData (ord_no, purch_amt, ord_date, customer_id, salesman_id) values
('7008', 700.3, '2012-09-27', '3004', '5004');
select * from orderData;

 * mysql+mysqldb://root:***@127.0.0.1/testdb
1 rows affected.
6 rows affected.

[('70001', 150.5, datetime.date(2012, 10, 5), '3005', '5002'),
 ('70009', 270.65, datetime.date(2012, 9, 10), '3001', '5005'),
 ('70002', 65.26, datetime.date(2012, 10, 5), '3002', '5001'),
 ('70004', 110.5, datetime.date(2012, 8, 17), '3009', '5003'),
 ('70007', 948.5, datetime.date(2012, 9, 10), '3005', '5002'),
 ('7008', 700.3, datetime.date(2012, 9, 27), '3004', '5004')]

In [26]:
# (a) Install the ‘sqldf’ and ‘Gifi’ packages. Load the packages. Also load the ‘mammals’
# dataset. Refer to the help page of the dataset for more information about the dataset.
# [05 marks]
# install.packages("sqldf")
# install.packages("Gifi")
library(sqldf)
library(Gifi)
data(mammals)

# (b) Count the number of rows in the ‘mammals’ data using sqldf function. Compare your
# answer with the R counterpart. [15 marks]
sqldf("SELECT COUNT(*) AS num_rows FROM mammals")
nrow(mammals)

# (c) Select all the columns and rows from ‘mammals’ data and put it into a variable ‘mammal’.
# [10 marks]
mammal <- sqldf("SELECT * FROM mammals limit 6")

# (d) Select the first two columns of the ‘mammals’ data and put it into a variable ‘mammals First2Cols’. [10 marks]
mammals_First2Cols <- sqldf("SELECT topincisors,bottomincisors FROM mammals limit 6")

# (e) Print the first 6 rows of the ‘mammals’ dataset using sqldf function. [10 marks]
sqldf("SELECT * FROM mammals limit 6")

# (f) How many mammals with more than two top molars? [10 marks]
sqldf("SELECT COUNT(*) AS num_mammals FROM mammals WHERE topmolars > 2")

# (g) How many mammals with more than two top molars and less than three bottom molars?
# [15 marks]
sqldf("SELECT COUNT(*) AS num_mammals FROM mammals WHERE topmolars > 2 AND bottommolars < 3")

# (h) How many mammals with more than four premolars? [10 marks]
sqldf("SELECT COUNT(*) AS num_mammals FROM mammals WHERE (toppremolars + bottompremolars) > 4")

# (i) Using this dataset, what is the average number of teeth for a mammal? [15 marks]
sqldf("SELECT AVG(toppremolars + bottompremolars + topmolars + bottommolars + topincisors + bottomincisors) AS avg_teeth FROM mammals")

  num_rows
1 66

[1] 66

  topincisors bottomincisors topcanines bottomcanines toppremolars
1 4           5              2          2             4
2 4           4              2          2             5
3 4           3              2          1             4
4 4           4              2          2             5
5 3           4              2          2             4
6 3           4              2          2             3
  bottompremolars topmolars bottommolars
1 4               2         2
2 5               2         2
3 4               2         2
4 5               2         2
5 4               2         2
6 4               2         2

  num_mammals
1 0

  num_mammals
1 0

  num_mammals
1 54

  avg_teeth
1 16.4697

**_End of the paper_**